# Generated by Django 3.1.5 on 2021-01-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_photo',
        ),
    ]
