# Generated by Django 3.1.5 on 2021-01-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210118_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='draft',
        ),
    ]
