# Generated by Django 3.1.5 on 2021-01-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210119_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
