# Generated by Django 3.1.5 on 2021-01-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_comments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='date',
            new_name='datetime',
        ),
    ]
